sudo: required

services:
  - docker

before_install:
  - docker pull instrumentisto/glide
  - docker run --rm -it -v $(pwd):/go/src/github.com/21stio/go-ideahub -w /go/src/my/pkg/name \
      instrumentisto/glide install